# Generated by Django 4.2 on 2023-04-25 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowing', '0002_alter_borrowing_actual_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Hard'), ('PAID', 'Soft')], max_length=8)),
                ('type', models.CharField(choices=[('PAYMENT', 'Hard'), ('FINE', 'Soft')], max_length=8)),
                ('session_url', models.URLField(default='www.kostyl.com')),
                ('session_id', models.CharField(default='www.kostyl.com', max_length=255)),
                ('borrowing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='borrowing.borrowing')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
