# Generated by Django 4.1 on 2023-04-24 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="daylee_fee",
            new_name="daily_fee",
        ),
    ]
