# Generated by Django 4.1 on 2023-04-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_rename_daylee_fee_book_daily_fee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=63)),
                ("last_name", models.CharField(max_length=63)),
                ("pseudonim", models.CharField(blank=True, max_length=63, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.ManyToManyField(related_name="books", to="books.author"),
        ),
    ]
