# Generated by Django 4.1 on 2023-04-24 14:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_author_remove_book_author_book_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ("title",)},
        ),
    ]
