# Generated by Django 4.2 on 2023-04-25 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='pseudonim',
            new_name='pseudonym',
        ),
    ]
