# Generated by Django 4.1 on 2023-04-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="actual_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
